Eliminate warning due to redefinition of secret=
/Users/glenn/src/secretsharing/lib/secretsharing/shamir/secret.rb:96: warning: method redefined; discarding old secret=